spring.datasource.url=jdbc:mysql://localhost:3306/fsad_skill12
spring.datasource.username=root
spring.datasource.password=Manoj@9876

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080